### PR TITLE
ApplicationCharge endpoint support. Tests for the #91.

### PR DESCRIPTION
**Pull request by amwolff**
This PR adds ApplicationCharge endpoint support. It also includes #91 (original commit) with extensive tests as it was requested which, in effect, renders #91 resolved.

cc: @orian

### CODE REVIEW

**Comment by amwolff** [comment]
I think that I might have accidentally overwritten changes from #102 with this commit (CI failure). This is now fixed. I also think that next time it might be more convenient to use something like https://godoc.org/github.com/stretchr/testify/assert#Equal instead of `DeepEqual`'s and then testing just one field (although it's redundant in here).

**Comment by dlebech** [comment]
@amwolff testify is indeed a nice library. I can't remember why I didn't use it when I created go-shopify to be honest, but it was either I didn't know about the library at the time or I wanted to reduce dependencies :-) Thanks for the PR btw! I'll review it later today when I have a bit more time, unless someone beats me to it :beers:

**Review by dlebech — APPROVED** [review]
Thanks for the PR @amwolff :trophy: And thanks for finishing the tests from #91 :100: :1st_place_medal:

**Comment by dlebech** [comment]
Also, sorry for the delay. Yesterday was shorter than I thought :thinking: :slightly_smiling_face:

**Pull request merged**
